# Generated by Django 4.2.7 on 2023-11-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HardwareInfo",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("hostname", models.TextField(max_length=255)),
                ("Host_ip", models.TextField(max_length=255)),
                ("cpu_model", models.TextField(max_length=255)),
                ("cpu_architecture", models.TextField(max_length=255)),
                ("cpu_cores", models.IntegerField()),
                ("cpu_logical_cores", models.IntegerField()),
                ("cpu_Frequency", models.TextField(max_length=255)),
                ("load_1min", models.IntegerField()),
                ("load_5min", models.IntegerField()),
                ("load_15min", models.IntegerField()),
                ("memory_total", models.TextField(max_length=255)),
                ("memory_available", models.TextField(max_length=255)),
                ("mamory_used", models.TextField(max_length=255)),
                ("memory_percent", models.TextField(max_length=255)),
                ("disk_total", models.TextField(max_length=255)),
                ("disk_free", models.TextField(max_length=255)),
                ("disk_used", models.TextField(max_length=255)),
                ("disk_percent", models.FloatField()),
                ("boot_time", models.DateTimeField()),
                ("boot_uptime", models.TimeField()),
                ("batery_percent_charge", models.TextField(max_length=255)),
                ("batery_power_is_plug", models.TextField(max_length=255)),
                ("system_version", models.TextField(max_length=255)),
                ("system_system_type", models.TextField(max_length=255)),
                ("system_distribution", models.TextField(max_length=255)),
                ("network_bytes_recv", models.TextField(max_length=255)),
                ("network_bytes_send", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("idade", models.IntegerField()),
            ],
        ),
    ]
